### ISSUE TITLE
"TOUCH_PANNER_DISABLED : false" doesn't work since 0.10.3

### ISSUE THREAD

**Issue by dokydok** [immersive-web/webvr-polyfill#314]
setting:
new window.WebVRPolyfill({
  TOUCH_PANNER_DISABLED : false,
});
have no effect since 0.10.3, no panning when touching the screen.

**Comment by jsantell** [comment]
TOUCH_PANNER_DISABLED was removed in 0.10.0 -- it can be implemented with something like: https://github.com/immersive-web/webvr-polyfill/blob/v0.9.41/src/touch-panner.js

**Comment by dokydok** [comment]
It probably should be added to the release notes

**Comment by jsantell** [comment]
Yeah, I must've forgot to add it -- it's the same reason the mouse and keyboard controls were removed -- outside of the scope of supporting WebVR and difficult to anticipate all potential input mechanisms outside of VR. I'll add it to the notes, thanks for pointing it out!

**Comment by dustinkerstein** [comment]
Are there any examples available of the new touch-panner in use? Thanks!

**Comment by jsantell** [comment]
There's nothing in the polyfill for that, no -- but in the future there could be different 'CardboardVRDisplays' in user land that are powered by a touch panner, or mouse and keyboard for example

**Comment by jsantell** [comment]
Added to 0.10.0 release notes -- closing this issue, but would be open to adding links to the README of other implementations of things like TouchPannerVRDisplay, KeyboardMouseVRDisplay, etc.

**Comment by didacher** [comment]
Hi @jsantell I need to enable vertical move of touchpanner in the CardboardVRDisplay. Do you thing creating a TouchPannerVRDisplay is good idea or just modifiying the old TouchPanner of CardboardVRDisplay to enable phi updates from the touch is enought? If so, what do you think shoud be enough to add because I tried to add the phi in the getOrientation of touchpanner but the result does not respect desired angles
