### ISSUE TITLE
Is wake lock base64 video required ?

### ISSUE THREAD

**Issue by yuccai** [immersive-web/webvr-polyfill#350]
Hi,
I'm using `0.10.10` `webvr-polyfill` and my content security policy directive prevents me to load any media.
I would like to know if i can still use this polyfill by disabling wake lock feature and its `no sleep video` to not load its base 64 video content.

**Comment by jsantell** [comment]
Wakelock is weird -- the cardboard-vr-display dependency uses [nosleep.js](https://github.com/immersive-web/cardboard-vr-display/blob/de59375309e637edbd3fd5e5213eac602930bb2b/package.json#L42) to handle this, and it's always been a fragile thing, requiring updates for every new iOS version. Maybe there's some promise in the new [Wakelock API](https://developers.google.com/web/updates/2018/12/wakelock) proposal?

I hope there's some way to achieve the same effect without the base64 video string in the case of using CSP, but it's been awhile since I've looked at this area of code.

**Comment by jsantell** [comment]
You can also use [this](https://github.com/immersive-web/webvr-polyfill/blob/ceb80d0e2d1d66e318782e30d89e0a09ca4857cd/src/config.js#L53) option so the cardboard-vr-display does not attempt to use the wakelock as a stopgap potentially

**Comment by yuccai** [comment]
It does the job :+1:, thanks
